### ISSUE TITLE
Karma  Gulp task does not work

### ISSUE THREAD

**Issue by kokujin** [arvindr21/slush-meanjs#5]
Sorry to give you a hard time @arvindr21 . I just tried the Karma test and I got this

````
[09:40:18] Error: Invalid glob argument: undefined
    at Gulp.src (/home/kokujin/Development/research/angular_test/node_modules/gulp/node_modules/vinyl-fs/lib/src/index.js:21:11)
    at Gulp.<anonymous> (/home/kokujin/Development/research/angular_test/gulpFile.js:61:10)
    at module.exports (/home/kokujin/Development/research/angular_test/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/kokujin/Development/research/angular_test/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/kokujin/Development/research/angular_test/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/kokujin/Development/research/angular_test/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
````

**Comment by arvindr21** [comment]
Closing as no response
